api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Shopsy/ProductCatalog/Main/Ui/Http/Rest/Model']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:   ['application/ld+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        csv:      ['text/csv']
        html:     ['text/html']
