doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 'mariadb-10.5.8'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            uuid: App\Common\Infrastructure\Persistence\Doctrine\Type\Id
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CommonStoredDomainEvent:
                type: xml
                dir: '%kernel.project_dir%/src/Common/Infrastructure/Persistence/Doctrine/Event/Mapping'
                is_bundle: false
                prefix: App\Common\Domain\Event
            ProductCatalogProduct:
                type: xml
                dir: '%kernel.project_dir%/src/Shopsy/ProductCatalog/Main/Infrastructure/Persistence/Doctrine/Product/Projection/Mapping'
                is_bundle: false
                prefix: App\Shopsy\ProductCatalog\Main\Domain\Product